APPLY_FIXES: none
SHOW_ELAPSED_TIME: true
IGNORE_GITIGNORED_FILES: true
DISABLE:
  - SPELL
FILEIO_REPORTER: true
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
GO_GOLANGCI_LINT_CLI_LINT_MODE: project
GO_GOLANGCI_LINT_CONFIG_FILE: LINTER_DEFAULT
GO_REVIVE_CLI_LINT_MODE: project
GO_REVIVE_ARGUMENTS: ./...
GO_REVIVE_CONFIG_FILE: LINTER_DEFAULT
