version: 2.1

orbs:
  go: circleci/go@3.0.2

jobs:
  MegaLinter:
    docker:
      - image: oxsecurity/megalinter-go:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "export CI_JOB_URL=$CIRCLE_BUILD_URL" >> "$BASH_ENV"
            # Export `CI_JOB_URL` for MegaLinter API Reporter
            echo "export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY" >> "$BASH_ENV"
            . "$BASH_ENV"
      - run:
          name: Run MegaLinter
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    parameters:
      go-version:
        type: string
    executor:
      name: go/default
      tag: << parameters.go-version >>
    steps:
      - checkout
      - go/with-cache:
          steps:
            - go/mod-download
            - go/test:
                coverprofile: coverage.txt
                covermode: atomic
      - run:
          name: Upload Coverage Report
          # Do not use Codecov Orb, download Codecov CLI and upload coverage
          # report by hand.
          #
          # Codecov Orb v5.4.0 added `--retry-all-errors` into Curl command.
          # That option, which is added in Curl 7.71.0, is not available in Go
          # executor 1.17-.
          #
          # https://github.com/codecov/codecov-circleci-orb/commit/12e27248956a647fe5ca2ad3898fb14cb91f9c4a
          # https://github.com/codecov/wrapper/commit/61989fd8503ba5dd9b6c3f340d1196ca75d0303b
          # https://github.com/codecov/wrapper/pull/54
          # https://daniel.haxx.se/blog/2020/06/24/curl-7-71-0-blobs-and-retries/
          # https://curl.se/docs/manpage.html#--retry-all-errors
          command: |
            CODECOV="$(mktemp -d)/codecov/bin/codecov"
            # `mktemp` on codecov doesn't support long options, use short
            # options instead.

            curl --output "${CODECOV}" --create-dirs --location --silent --show-error https://cli.codecov.io/latest/linux/codecov
            chmod +x "${CODECOV}"

            "${CODECOV}" upload-process --file coverage.txt --slug "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            # `CIRCLE_PROJECT_ID` is a UUID, do not use it.

workflows:
  CI:
    jobs:
      - MegaLinter:
          context: megalinter
      - test:
          matrix:
            parameters:
              go-version:
                - "1.14"
                - "1.15"
                - "1.16"
                - "1.17"
                - "1.18"
                - "1.19"
                - "1.20"
                - "1.21"
                - "1.22"
                - "1.23"
                - "1.24"
          context: test
