version: 2.1

orbs:
  go: circleci/go@2.2.4
  codecov: codecov/codecov@5.2.0

jobs:
  MegaLinter:
    docker:
      - image: oxsecurity/megalinter-go:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo "export CI_JOB_URL=$CIRCLE_BUILD_URL" >> "$BASH_ENV"
            # Export `CI_JOB_URL` for MegaLinter API Reporter
            echo "export DEFAULT_WORKSPACE=$CIRCLE_WORKING_DIRECTORY" >> "$BASH_ENV"
            . "$BASH_ENV"
      - run:
          name: Run MegaLinter
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    parameters:
      go-version:
        type: string
    executor:
      name: go/default
      tag: << parameters.go-version >>
    steps:
      - checkout
      - go/with-cache:
          steps:
            - go/mod-download
            - go/test:
                coverprofile: coverage.txt
                covermode: atomic
      - codecov/upload:
          files: coverage.txt

workflows:
  CI:
    jobs:
      - MegaLinter:
          context: megalinter
      - test:
          matrix:
            parameters:
              go-version:
                - "1.14"
                - "1.15"
                - "1.16"
                - "1.17"
                - "1.18"
                - "1.19"
                - "1.20"
                - "1.21"
                - "1.22"
                - "1.23"
