version: 2.1

orbs:
  go: circleci/go@1.12.0
  codecov: codecov/codecov@4.2.0

jobs:
  Mega-Linter:
    environment:
      DEFAULT_WORKSPACE: /root/project
    docker:
      - image: oxsecurity/megalinter-go:v8
        # checkov:skip=CKV_CIRCLECIPIPELINES_2:prefer mutable but stable tags
    steps:
      - checkout
      - run:
          command: |
            sh /entrypoint.sh
      - store_artifacts:
          path: megalinter-reports
  test:
    parameters:
      go-version:
        type: string
    executor:
      name: go/default
      tag: << parameters.go-version >>
    steps:
      - checkout
      - go/load-cache:
          key: &go-mod-cache-key v1-go-mod-<< parameters.go-version >>
      - go/mod-download
      - go/save-cache:
          key: *go-mod-cache-key
      - go/test:
          coverprofile: coverage.txt
          covermode: atomic
          coverpkg: ./...
      - codecov/upload

workflows:
  CI:
    jobs:
      - Mega-Linter
      - test:
          matrix:
            parameters:
              go-version:
                - "1.14"
                - "1.15"
                - "1.16"
                - "1.17"
                - "1.18"
                - "1.19"
                - "1.20"
                - "1.21"
                - "1.22"
                - "1.23"
